version: "3"
services: 
  webapp-core:
    build: .
    image: wa-core:v0.1
    ports:
      - 8080:5000
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development
    volumes:
      - /tmp/WebApplication/database:/WebApp-Core/database
    #networks:
    #
  sqlitebrowse:
    image: coleifer/sqlite-web
    ports:
      - 8000:8080
    volumes:
      - /tmp/WebApplication/database:/data
    environment:
      - SQLITE_DATABASE=sqlite
    #networks:

#volumes:
#  appdb:

#networks:
#  ???:
#    driver: bridge
