version: "2"
services: 
  webapp-core:
    build:
      context: .
      dockerfile: dockerfile.app
    image: wa-core:v0.1
    ports:
      - 5000:5000 # ustaw 80 na produkcji (ma działać na domenie http://prod2.fenu-experiment.pl/ )
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development
    volumes:
      - appdb:/WebApp-Core/database
    networks:
      - webapp
  sqlitebrowse:
    build:
      context: .
      dockerfile: dockerfile.db
    image: coleifer/sqlite-web
    ports:
      - 8081:8080 # ustaw 8080 na produkcji (ma działać na domenie http://prod2db.fenu-experiment.pl/ )
    volumes:
      - appdb:/data
    environment:
      - SQLITE_DATABASE=sqlite
    networks:
      - webapp

volumes:
  appdb:

networks:
  webapp:
    driver: bridge
