"""empty message

Revision ID: 6b5b3405aadd
Revises: 828754b4e9b0
Create Date: 2022-01-25 16:47:25.423164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5b3405aadd'
down_revision = '828754b4e9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dekodery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tekst', sa.Text(), nullable=True),
    sa.Column('wynik', sa.Text(), nullable=True),
    sa.Column('operacja', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dekodery_timestamp'), 'dekodery', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dekodery_timestamp'), table_name='dekodery')
    op.drop_table('dekodery')
    # ### end Alembic commands ###
